[default]
src = 'src'                                                   # the source directory
test = 'test'                                                 # the test directory
out = 'out'                                                   # the output directory (for artifacts)
libs = ['lib']                                                # a list of library directories
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]   # a list of remappings
libraries = []                                                # a list of deployed libraries to link against
cache = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config